<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Actief',
    'Are you sure you want to delete this user?' => 'Weet je zeker dat je deze gebruiker wilt verwijderen?',
    'Banned' => 'Banned',
    'Bind to IP' => 'Vastmaken aan IP',
    'Browser' => 'Browser',
    'Change own password' => 'Pas eigen wachtwoord aan',
    'Change password' => 'Wachtwoord aanpassen',
    'Changing password' => 'Wachtwoord aan het veranderen',
    'Changing password for user: ' => 'Wachtwoord aanpassen van gebruiker:',
    'Child permissions' => 'Child permissies',
    'Child roles' => 'Child rollen',
    'Code' => 'Code',
    'Confirmation Token' => 'Bevestigingstoken',
    'Create' => 'Nieuwe maken',
    'Created' => 'Gemaakt',
    'Creating permission group' => 'Permissie voor groep maken',
    'Current password' => 'Huidig wachtwoord',
    'Data' => '',
    'Delete' => 'Verwijderen',
    'Description' => 'Omschrijving',
    'E-mail' => '',
    'E-mail confirmed' => 'E-mail bevestigd',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'E-mail met activatie link verstuurd aan: <b>{email}</b>. De link is {minutes} minuten geldig.',
    'Edit' => 'Bewerken',
    'Editing' => 'Aan het bewerken',
    'Editing permission group' => 'Bewerkt permissies van groep',
    'Editing permission: ' => 'Bewerk permissie:',
    'Editing role: ' => 'Bewerk rol:',
    'Editing user: ' => 'Bewerk gebruiker:',
    'For example: 123.34.56.78, 168.111.192.12' => 'Bijvoorbeeld: 123.34.56.78, 168.111.192.12',
    'Group' => 'Groep',
    'ID' => '',
    'Inactive' => 'Inactief',
    'IP' => '',
    'Language' => 'Taal',
    'Login' => '',
    'Name' => 'Naam',
    'OS' => '',
    'Password' => 'Wachtwoord',
    'Password has been changed' => 'Wachtoord is aangepast',
    'Permission creation' => 'Permissie maken',
    'Permission groups' => 'Permissie groepen',
    'Permissions' => 'Permissies',
    'Permissions for role:' => 'Permissies voor rol:',
    'Refresh routes' => 'Ververs routes',
    'Refresh routes (and delete unused)' => 'Ververs routes (+verwijder)',
    'Registration IP' => 'Registratie IP',
    'Repeat password' => 'Herhaal wachtwoord',
    'Reset' => '',
    'Role creation' => 'Rollen maken',
    'Roles' => 'Rollen',
    'Roles and permissions' => 'Rollen en permissies',
    'Roles and permissions for user:' => 'Rollen en permissies voor gebruiker:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => 'Regel',
    'Save' => 'Opslaan',
    'Saved' => 'Opgeslagen',
    'Search' => 'Zoeken',
    'Search route' => 'Zoek route',
    'Settings for permission' => 'Instellingen voor permissie',
    'Show all' => 'Alles tonen',
    'Show only selected' => 'Toon alleen geselecteerde',
    'Status' => 'Status',
    'Superadmin' => '',
    'Token' => '',
    'Too many attempts' => 'Te vaak geprobeerd!',
    'Type' => '',
    'Updated' => 'Aangepast',
    'User' => 'Gebruiker',
    'User agent' => 'Browser',
    'User creation' => 'Gebruiker aangemaakt',
    'Users' => 'Gebruikers',
    'Visit Time' => 'Bezoektijd',
    'Visit log' => 'Bezoek log',
    'Wrong format. Enter valid IPs separated by comma' => 'Fout format: geef IPs op gescheiden door een komma',
    'Wrong password' => 'Fout wachtwoord',
    'You can not change own permissions' => 'Je kunt je permissies niet aanpassen',
];
