<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization' => 'Log in',
    'Captcha' => '',
    'Check your E-mail for further instructions' => 'Kijk in je e-mail voor verdere instructies',
    'Check your e-mail {email} for instructions to activate account' => 'Kijk in je email: {email} voor instructies om je account te activeren.',
    'Confirm' => 'Bevestig',
    'Confirm E-mail' => 'Bevestig email adres',
    'Continue' => 'Verder gaan',
    'Could not send confirmation email' => 'Kon email niet versturen',
    'E-mail' => 'E-mail',
    'E-mail confirmation for' => 'E-mail bevestiging voor',
    'E-mail confirmed' => 'E-mail bevestigd',
    'E-mail is invalid' => 'Je E-mail adres is niet geldig.',
    'Forgot password ?' => 'Wachtwoord vergeten?',
    'Incorrect username or password.' => 'Verkeerde gebruikersnaam of wachtwoord',
    'Login' => 'Inloggen',
    'Login has been taken' => 'Deze loginnaam is al bezet',
    'Password' => 'Wachtwoord',
    'Password recovery' => 'Wachtwoord herstel',
    'Password reset for' => 'Wachtwoord hersteld voor',
    'Recover' => 'Herstel',
    'Register' => 'Aanmelden',
    'Registration' => 'Aanmelden',
    'Registration - confirm your e-mail' => 'Aanmelden - bevestig je e-mail',
    'Remember me' => 'Onthoud mij',
    'Repeat password' => 'Herhaal wachtwoord',
    'This E-mail already exists' => 'Dit E-mail adres bestaat reeds.',
    'Token not found. It may be expired' => 'Token niet gevonden. Misschien is het verlopem?',
    'Token not found. It may be expired. Try reset password once more' => 'Token niet gevonden. Misschien is het verlopen? Probeer je wachtwoord nog eens te resetten.',
    'Too many attempts' => 'Te veel pogingen',
    'Unable to send message for email provided' => 'Kan bericht nier versturen voor email adres',
    'Username' => 'Gebruikersnaam',
    'You could not login from this IP' => 'Je mag niet vanaf dit IP adres inloggen',
];
